-- This is for syntax highlighting
return {
  "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "bibtex",
        "c",
        "c_sharp",
        "cmake",
        "comment",
        "commonlisp",
        "cpp",
        "css",
        "gitconfig",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "gowork",
        "html",
        "ini",
        "java",
        "javascript",
        "jq",
        "jsdoc",
        "json",
        "julia",
        "kotlin",
        "latex",
        "lua", 
        "lua patterns",
        "make",
        "markdown",
        "markdown_inline",
        "perl",
        "python",
        "r",
        "regex",
        "rust",
        "sql",
        "svelte",
        "swift",
        "toml",
        "typescript",
        "vue",
        "yaml"
      },
    },
}
